version: '3'

services: 
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      spring.datasource.url: jdbc:postgresql://database:5432/learningprj
      datasource.username: randomuser
      datasource.password: randompwd
    depends_on:
      - database
    ports: 
    - "8080:8080"

  database:
    image: "postgres:10"
    environment:
      POSTGRES_USER: randomuser
      POSTGRES_PASSWORD: randompwd
      POSTGRES_DB: learningprj
    ports:
      - "5432:5432"
